CREATE TABLE TB_BUDGET(
	BUDGET_NO NUMBER CONSTRAINT TB_BUDGET_PK PRIMARY KEY,
	BUDGET_CONTENT VARCHAR2(4000) NOT NULL,
	BUDGET_OPTION CHAR(1) DEFAULT '+'
		CONSTRAINT OPTION_PM CHECK(BUDGET_OPTION IN ('+','-')),
	BUDGET_AMOUNT NUMBER NOT NULL,
	BUDGET_LEFT NUMBER NOT NULL
);
COMMENT ON COLUMN TB_BUDGET.BUDGET_NO IS '번호';
COMMENT ON COLUMN TB_BUDGET.BUDGET_CONTENT IS '내용';
COMMENT ON COLUMN TB_BUDGET.BUDGET_OPTION IS '선택(입금 + /출금 - )';
COMMENT ON COLUMN TB_BUDGET.BUDGET_AMOUNT IS '변화량';
COMMENT ON COLUMN TB_BUDGET.BUDGET_LEFT IS '잔액';

--번호 생성기 SEQUENCE 객체 생성하기
CREATE SEQUENCE SEQ_BUDGET_NO NOCACHE;

--샘플 데이터 넣기
INSERT INTO TB_BUDGET 
VALUES(
SEQ_BUDGET_NO.NEXTVAL, '첫 월급!', '+', 3000000, 3000000
);
SELECT * FROM TB_BUDGET;
INSERT INTO TB_BUDGET 
VALUES(
SEQ_BUDGET_NO.NEXTVAL, '점심 돈까쓰', '-', 10000, 2990000
);
INSERT INTO TB_BUDGET 
VALUES(
SEQ_BUDGET_NO.NEXTVAL, '교보문고에서 책 구매', '-', '60000', 2930000
);
INSERT INTO TB_BUDGET 
VALUES(
SEQ_BUDGET_NO.NEXTVAL, '아빠가 용돈 주셨다!!', '+', '200000', 3130000
);
COMMIT;

